version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "kyle-recktenwald"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    assignees:
      - "kyle-recktenwald"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "kyle-recktenwald"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
