name: Java CI with Gradle and Java 17

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test jacocoTestReport

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.3.0
        with:
          args: |
            -Dsonar.projectKey=kyle-recktenwald_runners-util-java-backend-0.0.2
            -Dsonar.organization=kyle-recktenwald
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.java.binaries=build/classes/java/main,build/classes/java/test
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
